---
name: CI/CD WITH TEST CASE
on:
  push:
    branches:
      - main
jobs:
  dev-job:
    name: Run Dev Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: upgrade pip first
        run: |
          python -m pip install --upgrade pip
      - name: install dependecies
        run: |
          python -m pip install pytest
      - name: Run test_calculator.py
        run: python -m pytest

      - name: create build artifact
        run: |
          mkdir build
          cp -r app build/
          zip -r python-app-build.zip build
          path: python-app-build.zip


      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app-build
          path: python-app-build.zip

